# --- top section stays the same ---
url: "https://skmustakali.github.io"
baseurl: ""
repository: "skmustakali/skmustakali.github.io"
title: "Sk Mustak Ali, Ph.D."

author:
  avatar: "profile_Ali.jpg"     # put your photo at images/profile.jpg
  name: "Sk Mustak Ali"
  bio: "Postdoctoral Research Associate, Texas A&M University"
  location: "College Station, Texas, USA"
  affiliation: "Cyclotron Institute, Texas A&M University"
  email: "mustak@tamu.edu"
    # Show the address as the label (clickable)
  links:
    - label: "mustak@tamu.edu"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:mustak@tamu.edu"

  googlescholar: "https://scholar.google.com/citations?user=VN8HtMgAAAAJ&hl=en"
  orcid: "https://orcid.org/0000-0002-1018-5307"
#  pubmed: ""                         # remove the John Snow example
  researchgate: "https://www.researchgate.net/profile/Sk-Mustak-Ali?ev=hdr_xprf"
  linkedin: "sk-mustak-ali"
#  github: "skmustakali"               # <-- change from 'academicpages'
#  bluesky: ""                       # put your full URL or leave blank
